train:
  num_epochs: 10
  batch_size: 64
  learning_rate: 0.001
  
data:
  data_dir: "data"  # Tên folder chứa dữ liệu MNIST
  
model:
  input_dim: 784    # 28 * 28 ảnh được duỗi phẳng
  hidden_dim: 128   # Số nơ-ron lớp ẩn
  output_dim: 10    # 10 chữ số (0-9)